[package]
name = "Aries"
version = "0.0.0"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "8fc6515e8014b0890f62621ed85de932a03a00b6"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.Oracle]
local = '../aries-oracle'

[addresses]
aries = "0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3"